#!/bin/bash
# Write a beautiful code that passes the Betty checks
# Originally by Tim Britton (@wintermanc3r), multiargument added by
# Larry Madeo (@hillmonkey) *** preguntar

BIN_PATH="betty"
BETTY_STYLE="betty-style.pl"
BETTY_DOC="betty-doc.pl"
STATUS_CODE="0"

if [ "$#" = "0" ]; then
    echo "No arguments passed."
    exit 1
fi

for argument in "$@" ; do
    echo -e "\n========== $argument =========="
    ${BIN_PATH}/${BETTY_STYLE} "$argument"
    CODE=$?
    if (($CODE != 0)); then
        STATUS_CODE=$CODE
    fi
    ${BIN_PATH}/${BETTY_DOC} "$argument"
    CODE=$?
    if (($CODE != 0)); then
        STATUS_CODE=$CODE
    fi
done

exit $STATUS_CODE
